# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: Application de tarot
nom_equipe: insaperrault
code_equipe: 1d

theme: jekyll-theme-dinky
